# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  inspect_db_code:
    docker:
      - image: liquibase/liquibase:latest

    steps:
      - checkout
      - run:
          name: "Run Liquibase version"
          command: "liquibase --version"

      - run: 
          name: "Run Liquibase Quality Checks"
          command: "liquibase --changeLogFile=src/main/resources/db/changelog/changelog_version-3.2.oracle.sql checks run"

  
  build:
    docker:
      - image: maven:3.3-jdk-8
    steps:
    - checkout
    - run:
        name: "Build app changes"
        command: "echo hello world"
        # command: "mvn clean package -Dspring.datasource.url=jdbc:oracle:thin:@127.0.0.1:49161/xe -Dspring.datasource.username=system -Dspring.datasource.password=oracle -Dspring.liquibase.change-log=classpath:db/changelog/changelog_version-3.2.oracle.sql -Dserver.port=8086 -Duser.timezone=CST"


workflows:
  ci_workflow:
    jobs:
      - inspect_db_code
      - build:
          requires:
            - inspect_db_code
